In [1]:
import os

os.getcwd()

'C:\\Users\\armck\\VU_DABC\\DBC_project_1\\Resources'

In [2]:
import numpy as np
import csv
import pandas as pd

In [64]:
start_year = 1989
end_year = 2020
year_list = list(np.arange(start_year, end_year, 1))

f500_df_prelim = pd.DataFrame(columns=['rank', 'company', 'year'])

for year in year_list:
    
    path = f'csv/fortune500-{year}.csv'
    
    f500_df = pd.read_csv(path)
    f500_df['year'] = year
    
    f500_df_prelim = f500_df_prelim.append(f500_df)
    
    f500_df_prelim.reset_index()
    
    
f500_df = f500_df_prelim

listoflists = pd.DataFrame(f500_df['company'].value_counts()).reset_index().rename(columns={'index':'company', 'company':'occurance'})
f500_df_sort = listoflists.merge(f500_df, on='company', how='left')
f500_df_sort = f500_df_sort.loc[f500_df_sort['profit ($ millions)'] != 'N.A.']
f500_df_sort['profit ($ millions)'] = f500_df_sort['profit ($ millions)'].astype('float64')
df2 = f500_df_sort.groupby('company').max().sort_values('profit ($ millions)', ascending=False)
df2 = df2.loc[df2['occurance'] >= 25]
df2

,occurance,profit ($ millions),rank,revenue ($ millions),year
company,,,,,
Exxon Mobil,31,45220.0,4,452926.0,2019
Berkshire Hathaway,31,44940.0,295,247837.0,2019
AT&T,25,29450.0,56,170756.0,2019
Citigroup,25,24589.0,56,159229.0,2019
Microsoft,25,23150.0,250,110360.0,2019
...,...,...,...,...,...
OfficeMax,33,416.8,483,13270.2,2013
R.R. Donnelley & Sons,31,400.6,445,11603.0,2019
Tech Data,25,340.6,464,37239.0,2019
Graybar Electric,25,143.3,480,7202.5,2019
Owens & Minor,25,115.2,481,9838.7,2019

In [ ]:
f500_df['company'].value_counts().to_csv(f'Fortune500_Sort_{start_year}-{end_year}.csv')